name: "PR Checks"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run unit tests
        run: yarn test

  terraform-plan:
    name: "Run a plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        env:
          CDKTF_ECS_TFC_ORGANIZATION: cdktf-team
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_API_TOKEN }}
        with:
          terraformVersion: 1.4.6
          cdktfVersion: 0.16.1
          stackName: ecs-microservices-cdktf
          mode: plan-only
          githubToken: ${{ secrets.GITHUB_TOKEN }}
