name: "PR Checks"

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run unit tests
        run: yarn test

  terraform-plan:
    needs: unit-tests # only run if unit tests succeeded
    name: "Run a plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install

      - name: Generate module and provider bindings
        run: npx cdktf-cli get

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.1.0
        env:
          CDKTF_ECS_TFC_ORGANIZATION: cdktf-team
          TF_TOKEN_app_terraform_io: ${{ secrets.TFC_API_TOKEN }}
        with:
          terraformVersion: 1.4.6
          cdktfVersion: 0.16.1
          stackName: ecs-microservices-cdktf
          mode: plan-only
          githubToken: ${{ secrets.GITHUB_TOKEN }}
